### PR TITLE
Parsing fixes

### PR DESCRIPTION
**Pull request by jugglinmike**
Extend YAML parser

Some recent changes in Test262 rely on previously-unused aspects of the YAML
grammar. Update the simplified YAML parser contained in this project to support
them.

@leobalter @littledan @tschneidereit Any of you folks mind reviewing this and
merging it if it looks okay?

### CODE REVIEW

**Comment by littledan** [comment]
Thanks for following up with this. So that I can test your code, which is the test262 test that depends on this change? Is it committed in master?

**Comment by jugglinmike** [comment]
Actually, it looks like these changes aren't necessary in isolation. For full
context: I made them in support of [the "negative
reform"](https://github.com/tc39/test262/pull/778) patch that recently landed
in Test262. Although this change set does not introduce support for that new
format, it's a prerequisite. I was hoping that the review process would be
more streamlined if I submitted the work in two phases given that these changes
concern valid aspects of the YAML grammar. But since there's not actually a use
case for them in isolation, the separation probably doesn't make sense.

Now that the previously-mentioned Test262 patch has landed, that final commit
can be landed here, as well. I've introduced it to this branch.

It occurs to me that this patch removes support for the prior error format
outright. As far as I know, V8 is the only consumer of this project, so that be
acceptable.

**Comment by littledan** [comment]
For V8's part, I only care about the ToT test262-harness-py supporting the ToT test262; as long as that's preserved, I'm happy.

@tschneidereit are you consuming this project?

**Comment by littledan** [comment]
The changes all look look good to me by visual inspection. Note that we don't use test262.py in the V8 test setup. What do you think the chances are of landing this patchset? If it could land, it would help us advance to the new version of test262 requiring the monkeyaml changes.

**Comment by littledan** [comment]
I have verified that this yaml parser works for the test262 tests for me within V8's setup, and that the tests won't work without it :). So there's some more evidence for landing it.

**Comment by jugglinmike** [comment]
Hey Dan,

I stand by this patch, but I'm loathe to merge my own work on any project. I
consider your review to be sufficient verification, but I'd still rather you
did the honors. When we created the "test262-utils" GitHub organization, I
invited both you and @tschneidereit to become members. The GitHub UI lists
those invitations as "pending," so I suspect if you hunt around your account
panel (or your e-mail inbox), you will find a message about the invitation and
a means to accept. From there, it's just a button push away!

**Pull request merged**
